server:
  port: 8081
spring: 
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 0 #数据库索引(默认为0)
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 10000 #客户端超时时间单位是毫秒 默认是2000 
    lettuce: 
      pool: 
        max-active: 8 #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8 #最大等待连接中的数量,设 0 为没有限制
        max-wait: 5
        min-idle: 0
      shutdown-timeout: 200 
    jedis:
      pool:
        max-idle: 8 #连接池最大连接数（使用负数表示没有限制）
        max-wait: 5 #连接池最大阻塞等待时间（使用负数表示没有限制）
        min-idle: 0 #连接池中最小的空闲连接（使用负数表示没有限制）
logging:
  config: classpath:logback.xml
  path: /log  #当前盘符根目录下
  level:
    root: WARN
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework.security: WARN
    com.springms: DEBUG
    com.example.demo: INFO
    org.springframework.web: INFO
           